import GLAttributeInfo from "./Common/GLAttributeInfo.js";
import GLLinkedAttributesToBuffer from "./Common/GLLinkedAttributesToBuffer.js";
import GLBufferInfo from "./Common/GLBufferInfo.js";
import GLUniformInfoArrayBase from "./Common/GLUniformInfoArrayBase.js";
import GLUniformMatInfo from "./Common/GLUniformMatInfo.js";
import GLUniformVecInfo from "./Common/GLUniformVecInfo.js";
import type { UniformValueArrayFunction } from "./Common/GLUniformInfoArrayBase.js";
import GLProgramInfo from "./Common/GLProgramInfo.js";
import GameObject from "./GameObject.js";
import type FigureInfo from "./Common/Utils/FigureInfo.js";
import PerspectiveCamera from "./PerspectiveCamera.js";
export default class WebGLWrapper {
    private _glContext;
    constructor();
    initViewport(): void;
    resizeCanvas(perspectiveCamera: PerspectiveCamera): void;
    getAttribLocation(program: WebGLProgram, nameAttrib: string): number;
    createAttributeInfo(program: WebGLProgram, nameAttrib: string, componentsNumberPerVertexAttribute: number, stride: number, offset: number): GLAttributeInfo;
    linkAttributesToBuffer(attributesInfo: GLAttributeInfo[], bufferInfo: GLBufferInfo): GLLinkedAttributesToBuffer;
    createUniformVecInfo(program: WebGLProgram, nameUniform: string, value: number[], updateValue?: UniformValueArrayFunction | null): GLUniformVecInfo;
    createUniformMatInfo(program: WebGLProgram, nameUniform: string, value: number[], updateValue?: UniformValueArrayFunction | null): GLUniformMatInfo;
    enableVertexAttribArray(attribLocation: number): void;
    bindAttributesBuffer(attributesBufferInfo: GLLinkedAttributesToBuffer): void;
    setUniformValue(uniformInfo: GLUniformInfoArrayBase): void;
    setUniformVecValue(uniformVecInfo: GLUniformVecInfo): void;
    setUniformMatValue(uniformMatInfo: GLUniformMatInfo): void;
    getUniformLocation(program: WebGLProgram, nameUniform: string): WebGLUniformLocation;
    createVertexShader(vertexShaderSource: string): WebGLShader;
    createFragmentShader(fragmentShaderSource: string): WebGLShader;
    createShader(type: GLenum, shaderSource: string): WebGLShader;
    createBufferInfo(bufferData: number[]): GLBufferInfo;
    useProgram(program: WebGLProgram): void;
    createProgramInfo(vertexShader: WebGLShader, fragmentShader: WebGLShader): GLProgramInfo;
    createDefaultColorProgramInfo(): GLProgramInfo;
    drawArrays(drawMode: GLenum, firstVertex: number, countVertices: number): void;
    createGameObject(programInfo: GLProgramInfo, linkedAttributesToBuffer: GLLinkedAttributesToBuffer[], countVertices: number): GameObject;
    createPerspectiveCamera(): PerspectiveCamera;
    getDefaultColorGameObjectByFigureInfo(programInfo: GLProgramInfo, figureInfo: FigureInfo): GameObject;
    updatePerspectiveCameraByProgram(program: WebGLProgram, perspectiveCamera: PerspectiveCamera): void;
}
//# sourceMappingURL=WebGLWrapper.d.ts.map